//! Device enrollment protocol — invite-based onboarding for new devices.
//!
//! # Flow
//!
//! 1. Admin device generates an `EnrollmentInvite` (QR code or deep link)
//! 2. New device scans QR / opens link → submits `EnrollmentRequest`
//! 3. Admin approves (auto-approve if invite hasn't expired)
//! 4. New device receives `EnrollmentResult` with device ID + credentials
//! 5. New device registers auth credential (TOTP secret, WebAuthn key, etc.)
//!
//! # Security Model
//!
//! - Invites are signed with the admin device's key (BLAKE3-HMAC)
//! - Each invite has a single-use nonce and expiry
//! - Invite can be scoped to specific permissions
//! - Revocation is immediate (admin removes device from registry)

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::session::DevicePermissions;

/// An enrollment invite generated by an admin device.
///
/// Encode as JSON → base64 → QR code or `tcfs://enroll?data=...` deep link.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentInvite {
    /// Unique invite ID (UUID v4).
    pub invite_id: String,
    /// Single-use nonce (random 16 bytes, hex-encoded).
    pub nonce: String,
    /// Admin device ID that created the invite.
    pub created_by: String,
    /// Invite creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Invite expiry timestamp.
    pub expires_at: DateTime<Utc>,
    /// Permissions granted to the enrolled device.
    pub permissions: DevicePermissions,
    /// BLAKE3-HMAC signature of the invite fields (signed by admin's master key).
    pub signature: String,
    /// Optional: NATS server URL for the fleet.
    pub nats_url: Option<String>,
    /// Optional: S3/SeaweedFS endpoint for storage.
    pub storage_endpoint: Option<String>,
    /// Optional: human-readable description of the invite.
    pub description: Option<String>,
}

impl EnrollmentInvite {
    /// Create a new enrollment invite.
    ///
    /// `admin_device_id`: the device creating the invite.
    /// `master_key`: 32-byte master key for HMAC signing.
    /// `ttl_hours`: how long the invite is valid.
    pub fn new(
        admin_device_id: &str,
        master_key: &[u8; 32],
        ttl_hours: u64,
        permissions: DevicePermissions,
    ) -> Self {
        let invite_id = uuid::Uuid::new_v4().to_string();
        let mut nonce_bytes = [0u8; 16];
        rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut nonce_bytes);
        let nonce = hex::encode(nonce_bytes);
        let now = Utc::now();
        let expires_at = now + chrono::Duration::hours(ttl_hours as i64);

        let mut invite = Self {
            invite_id,
            nonce,
            created_by: admin_device_id.to_string(),
            created_at: now,
            expires_at,
            permissions,
            signature: String::new(),
            nats_url: None,
            storage_endpoint: None,
            description: None,
        };

        invite.signature = invite.compute_signature(master_key);
        invite
    }

    /// Compute BLAKE3-keyed-MAC of the invite fields.
    fn compute_signature(&self, master_key: &[u8; 32]) -> String {
        let payload = format!(
            "{}:{}:{}:{}:{}",
            self.invite_id,
            self.nonce,
            self.created_by,
            self.created_at.timestamp(),
            self.expires_at.timestamp(),
        );
        let mac = blake3::keyed_hash(master_key, payload.as_bytes());
        mac.to_hex().to_string()
    }

    /// Verify the invite signature against a master key.
    pub fn verify_signature(&self, master_key: &[u8; 32]) -> bool {
        let expected = self.compute_signature(master_key);
        // Constant-time comparison
        expected == self.signature
    }

    /// Check if the invite has expired.
    pub fn is_expired(&self) -> bool {
        Utc::now() > self.expires_at
    }

    /// Check if the invite is valid (not expired and signature matches).
    pub fn is_valid(&self, master_key: &[u8; 32]) -> bool {
        !self.is_expired() && self.verify_signature(master_key)
    }

    /// Encode the invite as a base64 JSON string (for QR code / deep link).
    pub fn encode(&self) -> anyhow::Result<String> {
        let json = serde_json::to_vec(self)?;
        Ok(base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            &json,
        ))
    }

    /// Decode an invite from a base64 JSON string.
    pub fn decode(encoded: &str) -> anyhow::Result<Self> {
        let json =
            base64::Engine::decode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, encoded)?;
        Ok(serde_json::from_slice(&json)?)
    }

    /// Generate a `tcfs://enroll?data=...` deep link URI.
    pub fn to_deep_link(&self) -> anyhow::Result<String> {
        Ok(format!("tcfs://enroll?data={}", self.encode()?))
    }
}

/// A request from a new device to enroll using an invite.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentRequest {
    /// The invite being redeemed.
    pub invite_id: String,
    /// Invite nonce (proves possession of the invite).
    pub nonce: String,
    /// Requested device name.
    pub device_name: String,
    /// Device's public key (age X25519).
    pub public_key: String,
    /// Device platform (e.g., "macos-aarch64", "ios", "linux-x86_64").
    pub platform: String,
}

/// Result of a successful enrollment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentResult {
    /// Assigned device ID (UUID v4).
    pub device_id: String,
    /// Assigned device name (may differ from requested).
    pub device_name: String,
    /// Device permissions.
    pub permissions: DevicePermissions,
    /// NATS server URL (if fleet sync is enabled).
    pub nats_url: Option<String>,
    /// Storage endpoint URL.
    pub storage_endpoint: Option<String>,
    /// Auth methods available (e.g., ["totp", "webauthn"]).
    pub available_auth_methods: Vec<String>,
}

// Need hex for nonce encoding
mod hex {
    pub fn encode(bytes: impl AsRef<[u8]>) -> String {
        bytes.as_ref().iter().map(|b| format!("{b:02x}")).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_invite_create_and_verify() {
        let master_key = [42u8; 32];
        let invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            24,
            DevicePermissions::default(),
        );

        assert!(!invite.is_expired());
        assert!(invite.verify_signature(&master_key));
        assert!(invite.is_valid(&master_key));

        // Wrong key should fail
        let wrong_key = [0u8; 32];
        assert!(!invite.verify_signature(&wrong_key));
    }

    #[test]
    fn test_invite_encode_decode_roundtrip() {
        let master_key = [42u8; 32];
        let invite =
            EnrollmentInvite::new("admin-device", &master_key, 24, DevicePermissions::admin());

        let encoded = invite.encode().unwrap();
        let decoded = EnrollmentInvite::decode(&encoded).unwrap();

        assert_eq!(invite.invite_id, decoded.invite_id);
        assert_eq!(invite.nonce, decoded.nonce);
        assert_eq!(invite.created_by, decoded.created_by);
        assert_eq!(invite.signature, decoded.signature);
        assert!(decoded.verify_signature(&master_key));
    }

    #[test]
    fn test_deep_link() {
        let master_key = [42u8; 32];
        let invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            1,
            DevicePermissions::read_only(),
        );

        let link = invite.to_deep_link().unwrap();
        assert!(link.starts_with("tcfs://enroll?data="));

        // Extract data param and decode
        let data = link.strip_prefix("tcfs://enroll?data=").unwrap();
        let decoded = EnrollmentInvite::decode(data).unwrap();
        assert_eq!(invite.invite_id, decoded.invite_id);
    }
}
